base_url = "http://vsbabu.org/twenties"
title = "SV@2020"
description = "before the moss covers the thoughts..."

compile_sass = false
generate_feeds = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

theme = "even"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

build_search_index = true


[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"


[extra]
even_title = "SV@2020"
katex_enable = false
author = "Satheesh Vattekkat"
even_menu = [
    {url = "$BASE_URL/..", name = "home"},
    {url = "$BASE_URL/", name = "blog"},
    {url = "$BASE_URL/about/", name = "about"},
]
date_format = "%a %b %e, %Y"
